// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWPyl_TpeIex6JoUE_JyG5ZsHeYfv4uPM',
    appId: '1:330992934906:web:564f71ed23f394bbee8e43',
    messagingSenderId: '330992934906',
    projectId: 'mesibotest-7ca99',
    authDomain: 'mesibotest-7ca99.firebaseapp.com',
    storageBucket: 'mesibotest-7ca99.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRyoAXDr1091pV9Nh7-9mf9EoVxP7CEcc',
    appId: '1:330992934906:android:2977835e1e956368ee8e43',
    messagingSenderId: '330992934906',
    projectId: 'mesibotest-7ca99',
    storageBucket: 'mesibotest-7ca99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtpSSax0q9p7tYNcUuHU-1MJNomtYuuV0',
    appId: '1:330992934906:ios:691e93b6e25fb176ee8e43',
    messagingSenderId: '330992934906',
    projectId: 'mesibotest-7ca99',
    storageBucket: 'mesibotest-7ca99.appspot.com',
    iosClientId: '330992934906-cqer8acohtm733ef74l6e1h83aoelhtn.apps.googleusercontent.com',
    iosBundleId: 'com.mesibo.firstapp',
  );
}
